### ISSUE TITLE
Error when creating new application

### ISSUE THREAD

**Issue by SamKr** [coderrio/Coderr.Server#62]
When creating a new application, the server throws an unspecified error. Sometimes there's a flyout from the top saying something like 'unable to create application :(', sometimes there's this error page:

![image](https://user-images.githubusercontent.com/1439763/37512258-e4f5d892-2901-11e8-8b4d-6ec6b06b8a53.png)

The application does get created though, and they work as expected, so there don't seem to be any breaking errors.

**Comment by jgauffin** [comment]
solved
