### ISSUE TITLE
Incorrect report count under 'Analyze reports'

### ISSUE THREAD

**Issue by SamKr** [coderrio/Coderr.Server#76]
The report count under 'Analyze reports' of an error always shows '48':

![Capture](https://user-images.githubusercontent.com/1439763/71884653-03827680-3139-11ea-96a5-4f8be716b9b3.PNG)

![Capture2](https://user-images.githubusercontent.com/1439763/71884660-0715fd80-3139-11ea-9f8a-5c08fedac318.PNG)

**Comment by jgauffin** [comment]
corrected, thanks
