### ISSUE TITLE
GUI: table rows hard to read due to low contrast

### ISSUE THREAD

**Issue by SamKr** [coderrio/Coderr.Server#83]
Maybe it's a problem with my screens, but I'm find the rows a bit hard to read because of the low contrast between the font color and background color:

![contrast](https://user-images.githubusercontent.com/1439763/78536572-5d551400-77ee-11ea-86c7-4a09613fc8e9.png)

Maybe the text should be a bit darker?

For the top bar, it works great:

![contrast2](https://user-images.githubusercontent.com/1439763/78536600-69d96c80-77ee-11ea-96f0-6276498e68f2.png)

**Comment by jgauffin** [comment]
Solved
